modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/decodinatorX/Liroth-Revamped-Forge/issues" #optional
[[mods]] #mandatory
modId="liroth" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Liroth Revamped" #mandatory
displayURL="https://github.com/decodinatorX/Liroth-Revamped-Forge" #optional
logoFile="liroth_icon.png" #optional
credits="" #optional
authors="Decodinator" #optional
description='''The Revamped Mod of Alternate Dimensions! [Forge]'''
[[dependencies.liroth]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.liroth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"